version: '3'

services:
  db:
    image: postgres:alpine
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=neoway-db"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - ./db/postgresql-data:/var/lib/postgresql/data

  backend:
    build: ./app/
    image: go-env
    volumes:
      - ./app/:/go/src/app/
    command: ["go", "run", "main.go"]
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db