version: '3'

services:
  db:
    image: neoway-db
    container_name: neoway-container-db
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=neoway-db"
      - "POSTGRES_PASSWORD=postgres"
    build: './db'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./app/assets/:/home/
      - ./db/postgresql-data:/var/lib/postgresql/data

  backend:
    build: ./app/
    image: go-env
    container_name: go-env-container
    volumes:
      - ./app/:/go/src/app/
    command: bash -c "sleep 3; go run main.go"
    ports:
      - "8080:8080"
    environment:
      - "INPUT_PATH=/go/src/app/assets/base_teste_sem_header.csv"
      - "HOST=192.168.25.109"
      - "PORT=5432"
      - "USER=postgres"
      - "PASSWORD=postgres"
      - "DBNAME=neoway-db"
      - "TABLENAME=banco_tutorial"
    # restart: on-failure
    depends_on:
      - db
    links:
      - db